import './globals.css';
import ToastComponent from './toastComponent';
import ContextProvider from '@/components/web3Context';

export const metadata = {
  title: 'minimalens',
  description: 'Generated by create next app',
}

/* -------------------------------------------------------------------------- */
/*                                   Layout                                   */
/* -------------------------------------------------------------------------- */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <body>{children}</body>
        <ToastComponent/>
      </ContextProvider>
    </html>
  )
}
