import Head from 'next/head';
import './globals.css';
import ToastComponent from './toastComponent';
import ContextProvider from '@/components/web3Context';
import LensAccountContextProvider from '@/components/lensAccountContext';

export const metadata = {
  title: 'minimalens',
  description: 'Generated by create next app',
}

/* -------------------------------------------------------------------------- */
/*                                   Layout                                   */
/* -------------------------------------------------------------------------- */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://lens.xyz/widget-styles.css" />
      </head>
      <LensAccountContextProvider>
        <ContextProvider>
          <body>
            {children}
            <ToastComponent/>
          </body>
        </ContextProvider>
      </LensAccountContextProvider>
    </html>
  )
}
