import './globals.css'
import { Inter } from 'next/font/google'
import NavComponent from '../components/navComponent'
import ContextProvider from '@/components/accountContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'minimalens',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <header className="w-screen z-20 top-0 fixed bg-transparent px-4 lg:px-6 py-2.5">
          <NavComponent/>
        </header>
        <body className="z-10 relative">{children}</body>
      </ContextProvider>
    </html>
  )
}
